# Netlify configuration file

[build]
  # This tells Netlify where our serverless function code is located.
  functions = "functions/"

# This rule makes our serverless function available at a clean URL.
# It proxies requests from /api/* to the correct function path.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
