# Netlify configuration file

[build]
  # This tells Netlify where our serverless function code is located.
  functions = "functions/"

# This rule makes our new serverless function available at a clean URL.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
